export const TICK_MS = 16
export const FEEDBACK_DURATION = 900
export const MUTATION_EVERY = 4
export const MUTATION_BONUS = 12
export const MUTATION_DURATION = 2500

export const STAGES = [
  {
    name: 'Microbe',
    emoji: '🦠',
    color: '#4CAF50',
    bg: '#F0FFF4',
    zoneWidth: 38,
    speed: 0.55,
    sciName: 'Prokaryota',
    period: '3,800,000,000 years ago',
    fact: 'The first life on Earth! Single-celled organisms with no nucleus.',
    special: "Survived without oxygen and shaped Earth's atmosphere.",
  },
  {
    name: 'Amoeba',
    emoji: '🫧',
    color: '#26A69A',
    bg: '#E8F5E9',
    zoneWidth: 34,
    speed: 0.65,
    sciName: 'Amoeba proteus',
    period: '1,800,000,000 years ago',
    fact: 'Can change shape and engulf food whole using pseudopods.',
    special:
      'First cells to develop a true nucleus — a giant leap in complexity.',
  },
  {
    name: 'Jellyfish',
    emoji: '🪼',
    color: '#42A5F5',
    bg: '#E3F2FD',
    zoneWidth: 30,
    speed: 0.75,
    sciName: 'Medusozoa',
    period: '600,000,000 years ago',
    fact: 'Have no brain, heart, or bones — yet they thrive!',
    special: 'One of the oldest multi-cellular animals still alive today.',
  },
  {
    name: 'Fish',
    emoji: '🐟',
    color: '#1E88E5',
    bg: '#E8F4FD',
    zoneWidth: 27,
    speed: 0.9,
    sciName: 'Actinopterygii',
    period: '530,000,000 years ago',
    fact: 'First animals to develop a backbone (vertebrae).',
    special:
      'Introduced fins, gills, and scales — blueprints for all vertebrates.',
  },
  {
    name: 'Octopus',
    emoji: '🐙',
    color: '#7B1FA2',
    bg: '#F3E5F5',
    zoneWidth: 24,
    speed: 1.05,
    sciName: 'Octopoda',
    period: '300,000,000 years ago',
    fact: 'Has three hearts and blue blood. Can solve puzzles!',
    special: 'Evolved intelligence completely independently from vertebrates.',
  },
  {
    name: 'Shark',
    emoji: '🦈',
    color: '#1565C0',
    bg: '#E3F2FD',
    zoneWidth: 21,
    speed: 1.2,
    sciName: 'Selachimorpha',
    period: '450,000,000 years ago',
    fact: 'Older than trees! Sharks predate forests on land.',
    special: 'Electroreceptors let them detect a single heartbeat underwater.',
  },
  {
    name: 'Frog',
    emoji: '🐸',
    color: '#558B2F',
    bg: '#F1F8E9',
    zoneWidth: 19,
    speed: 1.35,
    sciName: 'Anura',
    period: '250,000,000 years ago',
    fact: 'First vertebrates to develop vocal cords for communication.',
    special: 'Can absorb water through their skin — they never need to drink.',
  },
  {
    name: 'Lizard',
    emoji: '🦎',
    color: '#F57F17',
    bg: '#FFFDE7',
    zoneWidth: 17,
    speed: 1.5,
    sciName: 'Squamata',
    period: '200,000,000 years ago',
    fact: 'Some species can regrow lost tails using stored fat and cartilage.',
    special: 'First reptiles to fully conquer dry land with waterproof eggs.',
  },
  {
    name: 'Dinosaur',
    emoji: '🦕',
    color: '#6D4C41',
    bg: '#EFEBE9',
    zoneWidth: 15,
    speed: 1.65,
    sciName: 'Dinosauria',
    period: '230,000,000 years ago',
    fact: 'Ruled Earth for 165 million years — longer than mammals have existed.',
    special:
      'Modern birds are living dinosaurs — they never truly went extinct.',
  },
  {
    name: 'Rabbit',
    emoji: '🐇',
    color: '#EC407A',
    bg: '#FCE4EC',
    zoneWidth: 13,
    speed: 1.85,
    sciName: 'Leporidae',
    period: '55,000,000 years ago',
    fact: 'Teeth never stop growing — they must constantly gnaw to keep them short.',
    special: 'Eyes placed on the sides of the head give nearly 360° vision.',
  },
  {
    name: 'Wolf',
    emoji: '🐺',
    color: '#546E7A',
    bg: '#ECEFF1',
    zoneWidth: 11,
    speed: 2.05,
    sciName: 'Canis lupus',
    period: '800,000 years ago',
    fact: 'Can smell prey from 2.8 km away and hear sounds 10 km distant.',
    special: 'Pack social structure inspired early human tribal organization.',
  },
  {
    name: 'Bear',
    emoji: '🐻',
    color: '#5D4037',
    bg: '#EFEBE9',
    zoneWidth: 10,
    speed: 2.25,
    sciName: 'Ursidae',
    period: '20,000,000 years ago',
    fact: 'During hibernation the heart slows to just 8 beats per minute.',
    special:
      'Can remember food sources from years prior across vast territories.',
  },
  {
    name: 'Eagle',
    emoji: '🦅',
    color: '#FF8F00',
    bg: '#FFF8E1',
    zoneWidth: 9,
    speed: 2.5,
    sciName: 'Accipitridae',
    period: '36,000,000 years ago',
    fact: "Vision is 4–8× sharper than a human's. Can spot prey from 3 km up.",
    special: 'Hollow bones make them light yet stronger than solid bone.',
  },
  {
    name: 'Lion',
    emoji: '🦁',
    color: '#E65100',
    bg: '#FBE9E7',
    zoneWidth: 8,
    speed: 2.75,
    sciName: 'Panthera leo',
    period: '1,000,000 years ago',
    fact: "A lion's roar can be heard up to 8 km away.",
    special:
      'Only truly social big cat — pride cooperation enables larger hunts.',
  },
  {
    name: 'Primate',
    emoji: '🦧',
    color: '#4E342E',
    bg: '#FBE9E7',
    zoneWidth: 7,
    speed: 3.0,
    sciName: 'Hominidae',
    period: '15,000,000 years ago',
    fact: 'Share 96.9% of DNA with humans. Use tools and show empathy.',
    special: 'First species confirmed to grieve the death of family members.',
  },
  {
    name: 'Human',
    emoji: '🧬',
    color: '#1A237E',
    bg: '#E8EAF6',
    zoneWidth: 6,
    speed: 3.3,
    sciName: 'Homo sapiens',
    period: '300,000 years ago',
    fact: 'Largest brain-to-body ratio of any animal on Earth.',
    special: 'Only species to create written language, art, and space travel.',
  },
  {
    name: 'Cyborg',
    emoji: '🤖',
    color: '#006064',
    bg: '#E0F7FA',
    zoneWidth: 5,
    speed: 3.65,
    sciName: 'Homo technologicus',
    period: 'Near future',
    fact: 'Merging biological tissue with electronics to enhance human ability.',
    special: 'Neural implants can restore sight, movement, and memory.',
  },
  {
    name: 'Alien',
    emoji: '👽',
    color: '#1B5E20',
    bg: '#E8F5E9',
    zoneWidth: 4,
    speed: 4.0,
    sciName: 'Xenobiota',
    period: 'Unknown',
    fact: 'If life exists elsewhere, it likely evolved under radically different chemistry.',
    special:
      'Could use silicon, ammonia, or liquid methane instead of carbon and water.',
  },
  {
    name: 'Cosmic',
    emoji: '🌌',
    color: '#4A148C',
    bg: '#F3E5F5',
    zoneWidth: 3,
    speed: 4.4,
    sciName: 'Conscientia universalis',
    period: 'End of time',
    fact: 'A form of consciousness spread across star systems and dimensions.',
    special: 'Exists as pure energy — no need for a physical body.',
  },
  {
    name: 'Omniscient',
    emoji: '✨',
    color: '#BF360C',
    bg: '#FBE9E7',
    zoneWidth: 2,
    speed: 4.8,
    sciName: 'Deus cognoscens',
    period: 'Beyond time',
    fact: 'The final form. Knows all things across all timelines simultaneously.',
    special: 'You have completed every era of evolution. You are everything.',
  },
]
